version: '3.3'
services:
    backend-challenge:
        build: ./challenge-app
        container_name: my-backend-app
        ports:
           - "8000:8000"
        depends_on:
           - redis-app
    redis-app: 
        image: "redis:latest"
        container_name: my-redis-server
        ports:
           - "6379:6379"
